name: Build & Test

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install ShellCheck
      run: |
        sudo apt-get update
        sudo apt-get install shellcheck
        shellcheck --version

    - name: Install Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build & Test
      run: make build build-docker test
