name: Build & Test

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  workflow_dispatch:

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build & Test
      run: make build build-docker test
